### PR TITLE
Fixes issue with add model.kindOf check

### LINKED ISSUE #10: It almost worked `model.kindof is not a function`
I get this error
```
TypeDoc exiting with unexpected error:
TypeError: model.kindOf is not a function
```
versions
```
    "typedoc": "^0.20.28",
    "typedoc-plugin-pages-fork": "0.0.1",
    "typescript": "^4.2.2"
```

### PR DESCRIPTION
**Pull request by zofiag**
Fixes https://github.com/unstubbable/typedoc-plugin-monorepo/issues/10

### CODE REVIEW

**Comment by unstubbable** [comment]
Thanks. Do you have an example where this currently fails? I'd like to know what kind of model that is. So can you log the model for me and post the output here?

**Comment by zofiag** [comment]
Sure! I think it fails when monorepo plugin is combined with https://github.com/mipatterson/typedoc-plugin-pages.

These are the keys of a problematic model: `[ 'url', 'model', 'template', 'parent', 'name', 'pagesPlugin' ]` (the whole object was huge, hope the keys list is enough).

My dependencies:
```
 "devDependencies": {
    "typedoc-plugin-monorepo": // currently link to a fork,
    "typedoc": "^0.20.34",
    "typedoc-plugin-pages": "^1.1.0"
  },
```

**Comment by edqx** [comment]
Is it possible that this could be merged or looked at again? I could do with this for a project and I'm currently ~~running a submodule of my fork with this pr merged into it, not really ideal.~~ using yarn patch to manually patch code on installation.

**Comment by unstubbable** [comment]
@zofiag @edqx Sorry for not looking at this earlier. ... I tried to test this PR along with `typedoc-plugin-pages` (actually `typedoc-plugin-pages-fork` because of https://github.com/mipatterson/typedoc-plugin-pages/pull/41). I'm wondering whether you even want to use the TOC plugin that is included in `typedoc-plugin-monorepo`. In my testing this created duplicate TOC entries for the modules, because apparently `typedoc-plugin-pages` also creates those TOC entries.

Screenshot 2021-04-23 at 10 17 18

**Comment by edqx** [comment]
Removing `typedoc-plugin-monorepo` led to this.. Although I'm actually not sure what you mean by `TOC`, and how I can disable that.
image

**Comment by edqx** [comment]
I see, the toc plugin modifies the **t**able **o**f **c**ontents at the side of every page. Still not sure how I can disable it though, as using asgerjensen/typedoc-plugin-external-module-map didn't work for me, only one of my packages showed up.

**Comment by unstubbable** [comment]
This project is deprecated since [TypeDoc now supports monorepos out of the box](https://typedoc.org/guides/monorepo/).

**Pull request closed without merging**
